version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:18.4.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn set version berry
      - run: yarn add --dev eslint
      - run: yarn add eslint
      - run: echo "Hello World"
      - run: pwd && ls -la

